### ISSUE TITLE
회원가입 페이지

### ISSUE THREAD

**Issue by rayodesol** [neymaru/FOVE-Backend#6]
**Description**
- 회원가입 페이지 제작

**Todo**
- [x] db 구조 짜기
- [x] 중복 아이디 쿼리 처리
- [x] controllers > userController.js 의 res.send() 를 res.json() 으로 처리
- [x] axios 에러 처리
- [x] 몽고디비로 데이터 보내기
- [x] 아이디 중복 검사 버튼화
- [x] 일단 자동 로그인 가능

**ETC**
- 프론트와 연결 병행 중
- 4개 파일 작성/수정
